/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS'
 */
public class tictactoe extends javax.swing.JFrame {

    /**
     * Creates new form tictactoe
     */
    int a=1;
    int p=0;
    
    public tictactoe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   String b2=jButton2.getText();
   if(b2.equals("") )
   {
         if(a%2==0)
         {
             jButton2.setText("0");
         }
         else 
         {
             jButton2.setText("x");
         }
         a++;
         String b1=jButton1.getText();
         b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();

if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}}
  
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if(a%2==0)
         {
             jButton4.setText("0");
         }
         else 
         {
             jButton4.setText("x");
         }
         a++; String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
    
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(a%2==0)
         {
             jButton6.setText("0");
         }
         else 
         {
             jButton6.setText("x");
         }
         a++;
         String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
    
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if(a%2==0)
         {
             jButton8.setText("0");
         }
         else 
         {
             jButton8.setText("x");
         }
         a++; 
         String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
  
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if(a%2==0)
         {
             jButton9.setText("0");
         }
         else 
         {
             jButton9.setText("x");
         }
         a++;   
         String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
  
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
         if(a%2==0)
         {
             jButton1.setText("0");
         }
         else 
         {
             jButton1.setText("x");
         }
         a++;String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
         if(a%2==0)
         {
             jButton3.setText("0");
         }
         else 
         {
             jButton3.setText("x");
         }
         a++;String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    if(a%2==0)
         {
             jButton5.setText("0");
         }
         else 
         {
             jButton5.setText("x");
         }
         a++; 
         String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
  

         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(a%2==0)
         {
             jButton7.setText("0");
         }
         else 
         {
             jButton7.setText("x");
         }
         a++;    
String b1=jButton1.getText();
String b2=jButton2.getText();
String b3=jButton3.getText();
String b4=jButton4.getText();
String b5=jButton5.getText();
String b6=jButton6.getText();
String b7=jButton7.getText();
String b8=jButton8.getText();
String b9=jButton9.getText();
if(b1.equals(""))
{
    b1=""+p;
    
    p++;
}else
{
   if(b2.equals(""))
{
    b2=""+p;
    
    p++;
} 
   else
   {
       if(b3.equals(""))
{
    b3=""+p;
    
    p++;
} 
       else
       {
           if(b4.equals(""))
{
    b4=""+p;
    
    p++;
}else
           {
               if(b5.equals(""))
{
    b5=""+p;
    
    p++;
} 
               else
               {
                   if(b6.equals(""))
{
    b6=""+p;
    
    p++;
} else
                   {
                       if(b7.equals(""))
{
    b7=""+p;
    
    p++;
} 
                       else
                       {
                           if(b8=="")
{
    b8=""+p;
    
    p++;
} else
                           {
                              if(b9.equals(""))
{
    b9=""+p;
    
    p++;
}  
                              
                           }
                       }
                   }
               }
           }
           
       }
   }
}
if(b1.equals(b2)&&b2.equals(b3)&& !b1.equals("") )
{
    jLabel2.setText("won");
    System.out.println(b1+" "+b2+" "+b3);
}
else
{
    if(b4.equals(b5)&&b5.equals(b6)&&!b4.equals(""))
    {
        jLabel2.setText("won");
          System.out.println(b4+" "+b5+" "+b6);
    }
    else
    {
        if(b7.equals(b8)&&b8.equals(b9)&& !b7.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b7+" "+b8+" "+b9);
        }
        if(b1.equals(b4)&&b4.equals(b7)&& !b1.equals(""))
        {
            jLabel2.setText("won");
              System.out.println(b1+" "+b4+" "+b7 );
        }
        else
        {
            if(b2.equals(b5)&&b5.equals(b8)&& !b2.equals(""))
            {
                jLabel2.setText("won");
                  System.out.println(b2+" "+b5+" "+b8);
            }
            else
            {
                if(b3.equals(b6)&&b6.equals(b9)&& !b3.equals(""))
                {
                    jLabel2.setText("won");
                      System.out.println(b3+" "+b6+" "+b9);
                }
                else
                {
                    if(b1.equals(b5)&&b5.equals(b9)&& !b1.equals(""))
                    {
                        jLabel2.setText("won");
                          System.out.println(b1+" "+b5+" "+b9);
                    }
                    else
                    {
                        if(b3.equals(b5)&&b5.equals(b7)&& !b3.equals(""))
                                {
                                    jLabel2.setText("won");
                                      System.out.println(b3+" "+b5+" "+b7);
                                }
                        
                    }
                }
            }
        }
    }
}
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
